// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB20A6Ib7gtFFFuorT3QKLX_EyMr7RCDUI',
    appId: '1:896201231315:web:e240a1919c86085897bd26',
    messagingSenderId: '896201231315',
    projectId: 'the-trellis-4a580',
    authDomain: 'the-trellis-4a580.firebaseapp.com',
    storageBucket: 'the-trellis-4a580.firebasestorage.app',
    measurementId: 'G-JDY1DY6XHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3emb3kdiCYKuhiLVZwSO5f9m3uBHFvPQ',
    appId: '1:896201231315:android:d86231e2b9eb3df397bd26',
    messagingSenderId: '896201231315',
    projectId: 'the-trellis-4a580',
    storageBucket: 'the-trellis-4a580.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC62Lia4k3P1CGMnQgOBeQgKNCxilfTMEY',
    appId: '1:896201231315:ios:67b2c81f16edff3397bd26',
    messagingSenderId: '896201231315',
    projectId: 'the-trellis-4a580',
    storageBucket: 'the-trellis-4a580.firebasestorage.app',
    iosBundleId: 'com.usengineering.trellis',
  );
}
